zegal/sfdt-utils

- src/__tests__/utils.js
- src/index.ts
- src/queryBookmark.ts
- src/sfdt/__tests__/fixtures/bookmarkEndingInMultipleInlineSfdt.js
- src/sfdt/__tests__/fixtures/nestedConditionListWithOneChildToggleOff.js
- src/sfdt/__tests__/fixtures/nestedConditonWithParentOff.js
- src/sfdt/__tests__/toggleBookmark.test.js
- src/sfdt/processInlines.ts
- src/sfdt/toggleBookmark.ts
- src/stack.ts
1. Stack is used to know the relation between conditional block inside conditional block
2. If parent is toggle of, no child will have toggle off object
> Re-implemented togglebookmark off using stack

- .prettierrc
- package.json
- src/queryBookmark.ts
- src/sfdt/__tests__/fixtures/bookmarkEndingInMultipleInlineSfdt.js
- src/sfdt/__tests__/fixtures/listWithConditionSfdt.js
- src/sfdt/__tests__/fixtures/nestedConditionListWithOneChildToggleOff.js
- src/sfdt/__tests__/fixtures/nestedConditonWithParentOff.js
- src/sfdt/__tests__/fixtures/parentOnBothSiblingOff.js
- src/sfdt/__tests__/toggleBookmark.test.js
- src/sfdt/toggleBookmark.ts
fieldType = 0 - represents Field begin
fieldType = 1 - represents Field end
fieldType = 2 - represents field separator
cc. @p-mag @kirannbhatt
> Nested Condition re-implemented using fieldType 1

- package-lock.json
- package.json
- src/sfdt/__tests__/toggleBookmark.test.js
- src/sfdt/canUseListCondition.ts
- src/sfdt/processInlines.ts
- src/sfdt/toggleBookmark.ts
1. The number will be hidden when full list is hidden
cc @p-mag @kirannbhatt
> feature: condition for list added

- package.json
> version changed to v0.3.5

- package-lock.json
- package.json
- src/sfdt/__tests__/canUseListCondition.test.js
- src/sfdt/canUseListCondition.ts
- src/sfdt/toggleBookmark.ts
> fix: fix for alphabetical number

- package-lock.json
- package.json
- src/sfdt/__tests__/canUseListCondition.test.js
- src/sfdt/__tests__/fixtures/listWithConditionSfdt-2.js
- src/sfdt/__tests__/toggleBookmark.test.js
- src/sfdt/canUseListCondition.ts
- src/sfdt/toggleBookmark.ts
> numbering in children

- src/sfdt/__tests__/populate.test.js
- src/sfdt/populate.ts
@kkc-dev 
Removed the extra space for the field in populate
> Remove extra space in populate and updated test accordingly

- src/sfdt/__tests__/fixtures/bookmarkEndingInMultipleInlineSfdt.js
- src/sfdt/__tests__/toggleBookmark.test.js
- src/sfdt/processInlines.ts
- src/sfdt/toggleBookmark.ts
Condition to remove the block:
1. if the inline is within the condition i.e stackForInline is not empty
2. if the processed inline is empty and differs from the given block inline length
@kkc-dev
> Remove the block if the processed inline is empty within bookmarked condition

- src/sfdt/__tests__/fixtures/bookmarkEndingInMultipleInlineSfdt.js
- src/sfdt/__tests__/toggleBookmark.test.js
- src/sfdt/processInlines.ts
- src/sfdt/toggleBookmark.ts
> Revert "Remove the block if the processed inline is empty within bookmarked condition"

- package-lock.json
- package.json
- src/sfdt/__tests__/fixtures/deedSeparationSFDT-2.js
- src/sfdt/__tests__/toggleBookmark.test.js
- src/sfdt/toggleBookmark.ts
> fix: condition bookmark start from list and end in simple object

- src/__tests__/utils.js
- src/sfdt/__tests__/fixtures/tableConditionSfdt.js
- src/sfdt/__tests__/toggleBookmark.test.js
- src/sfdt/processInlines.ts
- src/sfdt/toggleBookmark.ts
- Fixed Conditions inside table cells.
- Added new tests for toggleBookmark inside table.
@kkc-dev @ankitaShrma @Anthony-Michel
> 2.27 condition table

- src/sfdt/numberFromList.ts
Check cases where the list id is -1
> Fix invalid key error when the list id is not a valid one

- package.json
- src/sfdt/__tests__/populate.test.js
- src/sfdt/populate.ts
see ticket ZG-3309
User can input large text, in which he can input line break that should be translated as new line in the sfdt structure
> Adding Logic for converting data line break into new inline

- package.json
- src/sfdt/populate.ts
hasFieldEnd will search for ending fieldtype. SO remove both from populate
> Remove field type from the inline in populate

- src/sfdt/__tests__/replaceSfdtBookmarks.test.js
- src/sfdt/replaceSfdtBookmarks.ts
> 3.00-update-sfdt-bookmark

- package.json
- src/sfdt/populate.ts
This is a test fix
I don't think we need text field now. According to my comment when I updated it, text is needed when we have fieldEnd part
I have tested on some doc, seems working for now
There are still some issues to be updated here, but for now this works
@kirannbhatt @Anthony-Michel
> Remove text addition in new inline

- package.json
- src/sfdt/__tests__/fixtures/nestedCrossRef.js
- src/sfdt/__tests__/populate.test.js
- src/sfdt/crossReference.ts
- src/sfdt/populate.ts
@kirannbhatt @p-mag @Anthony-Michel
> Allow populate crossref for uuid based bookmarks

- package.json
- src/sfdt/bookmarkHighlight.ts
- src/sfdt/bookmarkProcess.ts
cc @ankitaShrma @Anthony-Michel
> feat: pass extra cb to processBlock

- package.json
- src/sfdt/populate.ts
Remove font color in populate fields
@kirannbhatt @Anthony-Michel @p-mag
> Remove color in populate

- package.json
- src/sfdt/__tests__/fixtures/multiNestedCondition.js
- src/sfdt/__tests__/fixtures/nestedBookmark.js
- src/sfdt/__tests__/toggleBookmark.test.js
- src/sfdt/bookmarkHighlight.ts
- src/sfdt/bookmarkProcess.ts
- src/sfdt/toggleBookmark.ts
keep the inline rather than delete it if it has bookmarkType too
@kirannbhatt @p-mag @Anthony-Michel
> Update processPara to keep the bookmark inline from toggle

- package.json
- src/sfdt/toggleBookmark.ts
> Remove brackets in condition as per ZG-3098
